pipeline{
    agent any
    
    stages{
        stage('build'){
            steps{
                sh 'echo "Build is completed on `hostname`"'
            }
        }
        
        stage('test'){
            steps{
                sh 'echo "Build is completed on test stage"'
            }
        }
        
        stage('deploy'){
            steps{
                sh 'echo "Build is completed on deploy stage"'
            }
        }
    }
}
