pipeline{
    agent any
    
    stages{
        stage('build'){
            steps{
                sh '''
                echo "Build is completed on `hostname`"
                bash ${WORKSPACE}/linux/script.sh
                '''
            }
        }
        
        stage('test'){
            steps{
                sh 'echo "Build is completed on test stage"'
            }
        }
        
        stage('deploy'){
            steps{
                sh 'echo "Build is completed on deploy stage"'
            }
        }
    }
}
