apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        #command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        command: ["perl", "-elw", "$x = \"Hello world!\n\"; sleep (300); print $x;"]
      restartPolicy: Never
  backoffLimit: 4


