name: Trufflehog Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Trufflehog
      run: pip install trufflehog

    - name: Run Trufflehog scan
      run: trufflehog --regex .

    # Optionally, you can save the scan results as artifacts
    - name: Save Trufflehog scan results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: trufflehog-results
        path: trufflehog_report.json
