name: Trufflehog Scan Workflow

on:
  push:
    branches:
      - main

jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Run Trufflehog Scan
        uses: vishnugonela/Devops_7AM/trufflehog-action.yml
        with:
          repository_url: ${{ github.repository }}
